### ISSUE TITLE
I can't create Kinesis firerhose 

### ISSUE THREAD

**Issue by heungh** [aws-samples/amazon-elasticsearch-intro-workshop#10]
Hi, I have a trouble with studying ElasticSearch Workshop.

https://github.com/aws-samples/amazon-elasticsearch-intro-workshop/blob/master/en/lab1/README.md

According to this document, it should be successful to create kinesis firehorse with ElasticSearch. I don't understand why this error happened. I also changed the access policy for workshop-esdomain into" Allow open access to the domain" but it didn't work.
Error message is here : 
Error
Verify that the IAM role has access to the Elasticsearch domain: arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain

I have been looking at the error below all day long. What did I miss in the workshop? Besides, in the workshop, there is no explanation of type, But I should enter the type(What is it?).    
I also attached the json policy of firehorse:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "s3:AbortMultipartUpload",
                "s3:GetBucketLocation",
                "s3:GetObject",
                "s3:ListBucket",
                "s3:ListBucketMultipartUploads",
                "s3:PutObject"
            ],
            "Resource": [
                "arn:aws:s3:::workshop-firehose-backup-20210719-heungh",
                "arn:aws:s3:::workshop-firehose-backup-20210719-heungh/*"
            ]
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "lambda:InvokeFunction",
                "lambda:GetFunctionConfiguration"
            ],
            "Resource": "arn:aws:lambda:us-east-1:181136804328:function:%FIREHOSE_POLICY_TEMPLATE_PLACEHOLDER%"
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:GenerateDataKey",
                "kms:Decrypt"
            ],
            "Resource": [
                "arn:aws:kms:us-east-1:181136804328:key/%FIREHOSE_POLICY_TEMPLATE_PLACEHOLDER%"
            ],
            "Condition": {
                "StringEquals": {
                    "kms:ViaService": "s3.us-east-1.amazonaws.com"
                },
                "StringLike": {
                    "kms:EncryptionContext:aws:s3:arn": [
                        "arn:aws:s3:::%FIREHOSE_POLICY_TEMPLATE_PLACEHOLDER%/*"
                    ]
                }
            }
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVpcs",
                "ec2:DescribeVpcAttribute",
                "ec2:DescribeSubnets",
                "ec2:DescribeSecurityGroups",
                "ec2:DescribeNetworkInterfaces",
                "ec2:CreateNetworkInterface",
                "ec2:CreateNetworkInterfacePermission",
                "ec2:DeleteNetworkInterface"
            ],
            "Resource": "*"
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "es:DescribeElasticsearchDomain",
                "es:DescribeElasticsearchDomains",
                "es:DescribeElasticsearchDomainConfig",
                "es:ESHttpPost",
                "es:ESHttpPut"
            ],
            "Resource": [
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/*"
            ]
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "es:ESHttpGet"
            ],
            "Resource": [
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/_all/_settings",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/_cluster/stats",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/workshop-log/_mapping/100",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/_nodes",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/_nodes/*/stats",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/_stats",
                "arn:aws:es:us-east-1:181136804328:domain/workshop-esdomain/workshop-log/_stats"
            ]
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "logs:PutLogEvents"
            ],
            "Resource": [
                "arn:aws:logs:us-east-1:181136804328:log-group:/aws/kinesisfirehose/workshop-firehose:log-stream:*"
            ]
        },
        {
            "Sid": "",
            "Effect": "Allow",
            "Action": [
                "kinesis:DescribeStream",
                "kinesis:GetShardIterator",
                "kinesis:GetRecords",
                "kinesis:ListShards"
            ],
            "Resource": "arn:aws:kinesis:us-east-1:181136804328:stream/%FIREHOSE_POLICY_TEMPLATE_PLACEHOLDER%"
        },
        {
            "Effect": "Allow",
            "Action": [
                "kms:Decrypt"
            ],
            "Resource": [
                "arn:aws:kms:us-east-1:181136804328:key/%FIREHOSE_POLICY_TEMPLATE_PLACEHOLDER%"
            ],
            "Condition": {
                "StringEquals": {
                    "kms:ViaService": "kinesis.us-east-1.amazonaws.com"
                },
                "StringLike": {
                    "kms:EncryptionContext:aws:kinesis:arn": "arn:aws:kinesis:us-east-1:181136804328:stream/%FIREHOSE_POLICY_TEMPLATE_PLACEHOLDER%"
                }
            }
        }
    ]
}

**Comment by heungh** [comment]
I made the elasticsearch as version 7.0 and then created the firehorse successfully.  With v 6.8, I failed to create the firerhorse several time and edited the iam role to allow all actions like "es:*" but couldn't make it eventually. 
However I made es as version 5.6 and 7.0 and could create the kinesis firehorse successfully.  And es version 5.6 couldn't show the kibana dashboard with the error message.  I managed to make the firehorse and nearly finished the lab 3.  It will be better to review all processs of this workshop and check if there are some errors while following the process in the labs. :(

**Comment by syrinx05p** [comment]
Thank you for your feedback to create Kinesis Data Firehose delivery streams with Amazon ES 6.8 destination. I've reproduced on my end if Amazon ES version is 6.8 and the issue doesn't occur if ES version is 7.x. If you use ES 6.8 for the workshop, you need to map IAM role of a delivery stream to ES role. It looks version-specific issue between Amazon ES and Kinesis Data Firehose. 

https://github.com/aws-samples/amazon-elasticsearch-intro-workshop/tree/master/en/lab1#creating-an-amazon-es-role

"type" means mapping type for Elasticsearch. It's deprecated from Elasticsearch 7.0. Please read these guides for more details. 
- https://docs.aws.amazon.com/firehose/latest/dev/create-destination.html#create-destination-elasticsearch
- https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html

Sorry for inconvenience. This workshop focuses on latest Amazon ES version, please use latest Amazon ES version for the workshop.

We will improve the content. If you have any concerns, please let us know.

**Comment by heungh** [comment]
Thank you for the answer. It is really helpful!   Have a great day!!
