### ISSUE TITLE
Tenant iot can't load data

### ISSUE THREAD

**Issue by heungh** [aws-samples/amazon-elasticsearch-intro-workshop#11]
I've imported all objects and import all of them to iot tenants. And then I created user iot_developer and role iot_developer_role and mapped them.  However, I can't load the visualizations with error: "Failed to load the visualization"   
There is a lot of errors while following the workshop.  I'm afraid it can't be useful to customers. This workshop has some problems because of errors and  by wrong information.
I want for your team to check all contents of this workshop again.

**Comment by heungh** [comment]
I think the document might omit cluster permissions to iot_developer_role.  After adding crud to the cluster role, I can see the visualization and dashboard :)

**Comment by syrinx05p** [comment]
Thank you for feedback. I'd like to improve our contents for all customers. Could you check iot_developer and role iot_developer_role have appropriate tenant permissions?

https://github.com/aws-samples/amazon-elasticsearch-intro-workshop/blob/master/en/lab3/README.md#creating-a-new-amazon-es-role
```
Add "IoT" to "Tenant" in "Tenant permissions section", and choose [Read Only] from the pull-down menu on the right side of "Tenant".
```

Please let me know the error can be resolved even if these roles have appropriate permission.

**Comment by heungh** [comment]
I resolved it to add cluster permissions.
I added  "crud"  to iot_developer_role and "cluster_composite_ops_ro" to iot_reader_role.
Before adding cluster permissions to them, I can't access and load resources of IOT Tenet.
I'm not sure that I added the proper permission to them.  I really appreicate that you suggest right permission! :)

**Comment by syrinx05p** [comment]
Thank you for your response. It's interesting behavior. I'm sorry that I cannot reproduce same issue on my end. Permissions of roles on my Amazon ES 7.10 env are:

* _opendistro/_security/api/roles/iot_developer_role 
```
{
  "iot_developer_role" : {
    "reserved" : false,
    "hidden" : false,
    "cluster_permissions" : [ ],
    "index_permissions" : [
      {
        "index_patterns" : [
          "workshop-log-*"
        ],
        "dls" : "",
        "fls" : [ ],
        "masked_fields" : [ ],
        "allowed_actions" : [
          "crud"
        ]
      }
    ],
    "tenant_permissions" : [
      {
        "tenant_patterns" : [
          "IoT"
        ],
        "allowed_actions" : [
          "kibana_all_write"
        ]
      }
    ],
    "static" : false
  }
}
```

* GET _opendistro/_security/api/roles/iot_reader_role
```
{
  "iot_reader_role" : {
    "reserved" : false,
    "hidden" : false,
    "cluster_permissions" : [ ],
    "index_permissions" : [
      {
        "index_patterns" : [
          "workshop-log-*"
        ],
        "dls" : """{
  "bool": {
    "must": {
      "match": {
        "status": "OK"
      }
    }
  }
}""",
        "fls" : [ ],
        "masked_fields" : [
          "ipaddress"
        ],
        "allowed_actions" : [
          "read"
        ]
      }
    ],
    "tenant_permissions" : [
      {
        "tenant_patterns" : [
          "IoT"
        ],
        "allowed_actions" : [
          "kibana_all_read"
        ]
      }
    ],
    "static" : false
  }
}
```
If you use Amazon ES 7.9 or prior, I'd appreciate it if you try on Amazon ES 7.10.
