### ISSUE TITLE
jp/lab1/README.md - Lab1 - Open Distro ロールと IAM ロールの紐付け - 4

### ISSUE THREAD

**Issue by hirohisawatanabe** [aws-samples/amazon-elasticsearch-intro-workshop#3]
@smrmkt 
「Lab1 - Open Distro ロールと IAM ロールの紐付け - 4」に、
「先ほど作成した [opendistro_firehose_role] を選択します．」とありますが、
その前の「Amazon ES ロールの作成 - 5」では、「"Role name" に "workshop_firehose_delivery_role" と入力します．」
とありますので、

「先ほど作成した [opendistro_firehose_role] を選択します．」ではなく、
「先ほど作成した [workshop_firehose_delivery_role] を選択します．」が正しいでしょうか？

**Comment by smrmkt** [comment]
ご指摘ありがとうございます．正しい内容に修正しました．
